export const refs = {
  heroBackground: document.querySelector('.js_image'),
  modalBackground: document.querySelector('.js_image_modal'),
  developerFoto: document.querySelector('.js-dev-foto'),
  footerImage: document.querySelector('.js-footer-logo'),
  accordionContainer: document.querySelector('.js-accordion-container'),
  rootColor: document.documentElement,
  openmenu: document.querySelector('.js_menu_changecolor'),
  changecolor: document.querySelector('.change-theme'),
  form: document.querySelector('.js-footer-form'),

  inputNtf: document.querySelector('.js-contact-inp'),
  inputNtfModal: document.querySelector('.js-contact-inp-modal'),
  validNtf: document.querySelector('.js-valid-notify'),
  invalidNtf: document.querySelector('.js-invalid-notify'),
  validNtfModal: document.querySelector('.js-valid-notify-modal'),
  invalidNtfModal: document.querySelector('.js-invalid-notify-modal'),
  spinner: document.querySelector('.js-loader-footer'),
  btnFooter: document.querySelector('.js-btn-footer'),
  formModal: document.querySelector('.js-modal-form'),
  spinnerModal: document.querySelector('.js-loader-modal'),
  btnFooterModal: document.querySelector('.js-btn-modal'),

  modalOrder: document.querySelector('[data-modal]'),
  openModalBtn: document.querySelector('[data-modal-open]'),
  closeModalBtn: document.querySelector('[data-modal-close]'),

  projSlideWrap: document.querySelector('.proj-swiper-wrap'),
  body: document.querySelector('body'),
};
