export const refs = {
  heroBackground: document.querySelector('.js_image'),
  modalBackground: document.querySelector('.js_image_modal'),
  developerFoto: document.querySelector('.js-dev-foto'),
  accordionContainer: document.querySelector('.js-accordion-container'),
  rootColor: document.documentElement,
  openmenu: document.querySelector('.js_menu_changecolor'),
  changecolor: document.querySelector('.change-theme'),
  form: document.querySelector('.js-footer-form'),
  spinner: document.querySelector('.js-loader-footer'),
  btnFooter: document.querySelector('.js-btn-footer'),
  formModal: document.querySelector('.js-modal-form'),
  spinnerModal: document.querySelector('.js-loader-modal'),
  btnFooterModal: document.querySelector('.js-btn-modal'),

  modalOrder: document.querySelector('[data-modal]'),
  openModalBtn: document.querySelector('[data-modal-open]'),
  closeModalBtn: document.querySelector('[data-modal-close]'),
  // modalClose: document.querySelector('[data-btn-close]'),
  // formModalClose: document.querySelector('[data-form-close]'),
};
